# Generated by Django 3.0 on 2021-12-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complet',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_addedd',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='date_addedd',
            new_name='date_added',
        ),
    ]
