# Generated by Django 3.0 on 2022-01-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220104_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
