# Generated by Django 3.0 on 2022-01-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='wayshipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
            ],
        ),
    ]
